import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import Link from "next/link";


export default function Home() {
  const [count, setCount] = useState(0);
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="navbar-box shadow-xl">
          <div id="navbar-menu" className="inline-grid">
            <Link href="" className="transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 duration-300"><img src="/menu-hamburger.svg"></img></Link>
          </div>
          <div className="inline-grid grid-cols-3 content-center">
            <Link href="" className="nav-card">Something One</Link>
            <Link href="" className="nav-card">Something Two</Link>
            <Link href="" className="nav-card">Something Three</Link>
          </div>
        </div>
        <div className={styles.main}>
          <div>
            <p>You clicked {count} times</p>
            <button className="bg-zinc-400 hover:bg-zinc-300 text-white font-bold py-2 px-4 rounded" onClick={() => setCount(count + 1)}>Click me</button>
            <br />
            { count === 69 ? ( 
            <h1>NICE!!</h1>
            ) : null }
          </div>
          <Link className={styles.card} href={"/next_page"}>Next Page</Link>
        </div>
      </main>
    </>
  );
}
